set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
Plugin 'tpope/vim-fugitive'
" Nerdtree
Plugin 'scrooloose/nerdtree'
" Git plugin not hosted on GitHub
Plugin 'git://git.wincent.com/command-t.git'
" JS Beautify
Plugin 'maksimr/vim-jsbeautify'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" Install L9 and avoid a Naming conflict if you've already installed a
" different version somewhere else.
Plugin 'ascenator/L9', {'name': 'newL9'}
" Vim markdown folding zi or Zi to acivate apparently
Plugin 'nelstrom/vim-markdown-folding'
" Stuff for Ruby dev
Plugin 'vim-ruby/vim-ruby'
" Python folding
Plugin 'tmhedberg/simpylfold'
" Asciidoc config
Plugin 'asciidoc/vim-asciidoc'

" YAML Folding
Plugin 'pedrohdz/vim-yaml-folds'

" Fuzzy Finder
" :Files / :FZF
Plugin 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plugin 'junegunn/fzf.vim'

" Highlight bar
Plugin 'itchyny/lightline.vim'

" Multiple Cursors
"
"    start: <C-n> start multicursor and add a virtual cursor + selection on the match
"        next: <C-n> add a new virtual cursor + selection on the next match
"        skip: <C-x> skip the next match
"        prev: <C-p> remove current virtual cursor + selection and go back on previous match
"    select all: <A-n> start multicursor and directly select all matches
"
"You can now change the virtual cursors + selection with visual mode commands. For instance: c, s, I, A work without any issues. You could also go to normal mode by pressing v and use normal commands there.
"
"At any time, you can press <Esc> to exit back to regular Vim.
Plugin 'terryma/vim-multiple-cursors'


" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

" Syntax highlighting on
syntax on

" Set coloured cursor column and rows
:hi CursorLine   cterm=NONE ctermbg=lightblue ctermfg=white guibg=darkred guifg=white
:hi CursorColumn cterm=NONE ctermbg=lightblue ctermfg=white guibg=darkred guifg=white
" Comment out this next line, and uncomment the one after, to enable column/row highlighing
" to be toggled with \c
" :set cursorline! cursorcolumn!
:nnoremap <Leader>c :set cursorline! cursorcolumn!<CR>
" End of cursor config

" Enable mouse support
":set mouse=a
":set mousemodel=popup_setpos

" Fix some shite with NERDTree
autocmd vimenter * if !argc() | NERDTree | endif
let g:NERDTreeDirArrows=0

" Press F5 for spell checking hilighting. Move cursor to word then z= to open suggested fixes
map <f5> :setlocal spell! spelllang=en_gb<CR>

:set ruler
:set shiftwidth=2
:set laststatus=2
:set list
:set listchars=tab:>-

" Folding configuration
:setlocal foldmethod=syntax
inoremap <F9> <C-O>za
nnoremap <F9> za
onoremap <F9> <C-C>za
vnoremap <F9> zf

" Statusline
let g:currentmode={'n':'N ', 'no':'N·Operator Pending ', 'v':'V ', 'V':'V·Line ', '^V':'V·Block ', 's':'Select ', 'S':'S·Line ', '^S':'S·Block ', 'i':'I ', 'R':'R ', 'Rv':'V·Replace ', 'c':'Command ', 'cv':'Vim Ex ', 'ce':'Ex ', 'r':'Prompt ', 'rm':'More ', 'r?':'Confirm ', '!':'Shell ', 't':'Terminal '}

" Automatically change the statusline color depending on mode
function! ChangeStatuslineColor()
  if (mode() =~# '\v(n|no)')
    exe 'hi! StatusLine ctermfg=008'
  elseif (mode() =~# '\v(v|V)' || g:currentmode[mode()] ==# 'V·Block' || get(g:currentmode, mode(), '') ==# 't')
    exe 'hi! StatusLine ctermfg=005'
  elseif (mode() ==# 'i')
    exe 'hi! StatusLine ctermfg=004'
  else
    exe 'hi! StatusLine ctermfg=006'
  endif

  return ''
endfunction

" Find out current buffer's size and output it.
function! FileSize()
  let bytes = getfsize(expand('%:p'))
  if (bytes >= 1024)
    let kbytes = bytes / 1024
  endif
  if (exists('kbytes') && kbytes >= 1000)
    let mbytes = kbytes / 1000
  endif

  if bytes <= 0
    return '0'
  endif

  if (exists('mbytes'))
    return mbytes . 'MB '
  elseif (exists('kbytes'))
    return kbytes . 'KB '
  else
    return bytes . 'B '
  endif
endfunction

function! ReadOnly()
  if &readonly || !&modifiable
    return ''
  else
    return ''
endfunction

function! GitInfo()
  let git = fugitive#head()
  if git != ''
    return ' '.fugitive#head()
  else
    return ''
endfunction

set laststatus=2
set statusline=
set statusline+=%{ChangeStatuslineColor()}               " Changing the statusline color
set statusline+=%0*\ %{toupper(g:currentmode[mode()])}   " Current mode
set statusline+=%8*\ [%n]                                " buffernr
set statusline+=%8*\ %{GitInfo()}                        " Git Branch name
set statusline+=%8*\ %<%F\ %{ReadOnly()}\ %m\ %w\        " File+path
set statusline+=%#warningmsg#
set statusline+=%*
set statusline+=%9*\ %=                                  " Space
set statusline+=%8*\ %y\                                 " FileType
set statusline+=%7*\ %{(&fenc!=''?&fenc:&enc)}\[%{&ff}]\ " Encoding & Fileformat
set statusline+=%8*\ %-3(%{FileSize()}%)                 " File size
set statusline+=%0*\ %3p%%\ \ %l:\ %3c\                 " Rownumber/total (%)

hi User1 ctermfg=007
hi User2 ctermfg=008
hi User3 ctermfg=008
hi User4 ctermfg=008
hi User5 ctermfg=008
hi User7 ctermfg=008
hi User8 ctermfg=008
hi User9 ctermfg=007
