set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
Plugin 'tpope/vim-fugitive'
" Nerdtree
Plugin 'scrooloose/nerdtree'
" Git plugin not hosted on GitHub
Plugin 'git://git.wincent.com/command-t.git'
" JS Beautify
Plugin 'maksimr/vim-jsbeautify'
" git repos on your local machine (i.e. when working on your own plugin)
" Plugin 'file:///home/gmarik/path/to/plugin'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" Install L9 and avoid a Naming conflict if you've already installed a
" different version somewhere else.
Plugin 'ascenator/L9', {'name': 'newL9'}

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

" Syntax highlighting on
syntax on

" Set coloured cursor column and rows
:hi CursorLine   cterm=NONE ctermbg=lightblue ctermfg=white guibg=darkred guifg=white
:hi CursorColumn cterm=NONE ctermbg=lightblue ctermfg=white guibg=darkred guifg=white
" Comment out this next line, and uncomment the one after, to enable column/row highlighing
" to be toggled with \c
" :set cursorline! cursorcolumn!
:nnoremap <Leader>c :set cursorline! cursorcolumn!<CR>
" End of cursor config

" Enable mouse support
":set mouse=a
":set mousemodel=popup_setpos

" Fix some shite with NERDTree
autocmd vimenter * if !argc() | NERDTree | endif
let g:NERDTreeDirArrows=0

" Press F5 for spell checking hilighting. Move cursor to word then z= to open suggested fixes
map <f5> :setlocal spell! spelllang=en_gb<CR>
