require 'bundler'
Bundler::GemHelper.install_tasks


desc "Run the unit testing suite on this gem."
task :test do
  $LOAD_PATH.unshift File.expand_path(File.dirname(__FILE__) + '/lib')
  require 'usefuldb.rb'
  Dir.glob("./test/*_test.rb").each do |file|
   require file
  end
end