####################################################################################################
# @author 	David Kirwan https://github.com/davidkirwan
# @description 	Ruby Rake script to generate a simulated CPU load on a system.
#
# @usage 	rake simulate:cpuload
# 
# @date 	2013-07-14
####################################################################################################

### => Import libs
require 'fileutils'
require 'logger'
require File.dirname(__FILE__) + "/../lib/common.rb"

# Include lib/common/tasks
include Common::Tasks

# Setup variables
begin
  @log = Logger.new(STDOUT)
  @log.level = Logger::DEBUG
  @data = nil
  @date = DateString.now # Common::Tasks::DateString#now
rescue Exception => e
  raise e
end

#################################################################################
task :default => 'menu'

task :menu do
  @log.debug "Printing Welcome"

  puts welcome = <<-WELCOME
rake simulate:cpuload # Simulates a CPU load on a system
WELCOME
end
#################################################################################


namespace :simulate do

  desc "Simulate a CPU load"
  task :cpuload do
    @log.debug "Executing simulate:load task"

    tasktimer = Time.now    

    1000.times do |i|
      100000.downto(1) do |j|
        Math.sqrt(j) * i / 0.2
      end
    end
 
    @log.debug "Duration: #{Time.now - tasktimer} seconds"
  end

end

