path: c:/Users/Mamolian/Git/github/cloaked-octo-ninja/snippets/Ruby/Rake/lib
output: c:/Users/Mamolian/Git/github/cloaked-octo-ninja/snippets/Ruby/Rake/backup/tmp
archive: tar
encrypt: true
loglevel: 0
