####################################################################################################
# @author       David Kirwan https://github.com/davidkirwan
# @description  Rakefile
#
# @date         2013-07-12
####################################################################################################
# Imports
require 'logger'
require 'fileutils'
require File.dirname(__FILE__) + "/../lib/common.rb"

# Include lib/common/tasks
include Common::Tasks

# Setup variables
begin
  @log = Logger.new(STDOUT)
  @log.level = Logger::INFO
  @data = nil
  @date = DateString.now # Common::Tasks::DateString#now
rescue Exception => e
  raise e
end

# The default task is print the welcome message
task :default => 'menu'
task :menu do
  puts welcomeMsg = <<-MSG
rake create:backup  # Create the encrypted backup
MSG
end


# Read the config.yaml configuration file into the @data Hash
task :read_config do
  @data = ConfigReader.load(File.dirname(__FILE__) + "/config.yaml")
  @data["script"] = File.expand_path(File.dirname(__FILE__))

  if @data["loglevel"].to_i == 0
    @log.level = Logger::DEBUG
  elsif @data["loglevel"].to_i == 1
    @log.level = Logger::INFO
  elsif @data["loglevel"].to_i == 2
    @log.level = Logger::WARN
  elsif @data["loglevel"].to_i == 3
    @log.level = Logger::ERROR
  elsif @data["loglevel"].to_i == 4  
    @log.level = Logger::FATAL
  end
end

# Create an archive from the files in the @data["path"]
task :create_archive do
  @log.debug "Generating an archive from: #{@data["path"]}"
  
  backupPath = @data["path"]
  tempPath = @data["script"]

  argline = ""

  if @data["archive"] == 'tar' then 
    @data["tmpFilename"] = "#{tempPath}/#{@date}.tar.gz"
    @log.debug "Creating archive #{@data["tmpFilename"]}"

    argline = "tar -zcf #{@data["tmpFilename"]} #{backupPath}"
  else 
    @data["tmpFilename"] = "#{tempPath}/#{@date}.zip"
    @log.debug "Creating archive #{@data["tmpFilename"]}"

    argline = "zip #{@data["tmpFilename"]} #{backupPath}"
  end

  sh "#{argline}" do |ok, status|
    ok or fail "Command failed with status (#{status.exitstatus})"
  end
  
  @log.debug "Archive generation complete"
end


task :encrypt_archive do
  if @data["encrypt"]
    @log.debug "Encrypting the archive"

    begin 
      argline = "gpg -e -r #{@data["recipient"]} #{@data["tmpFilename"]}"

      sh "#{argline}" do |ok, status|
        ok or fail "Command failed with status (#{status.exitstatus})"
      end

    rescue Exception => e
      raise e
    end

    @log.debug "Encryption completed"
  end
end


namespace :create do
  
  desc "Create the encrypted backup"
  task :backup => [:read_config, :create_archive, :encrypt_archive] do    
    @log.debug "Backup generation complete"
  end
  
end



